### ISSUE TITLE
研究詳細

### ISSUE THREAD

**Issue by FukumotoHaruki** [Wakayama-SocSEL/Fukumoto#1]

**Comment by FukumotoHaruki** [comment]
標本数
gm_libreoffice2.csv
プルリクエスト：382
ファイル数：未確認
gm_openstack.csv
プルリクエスト数：384
ファイル数：2321

現在：openstackの20ファイルを確認済み
色々な言語があり、調べながらでないとできないので６時間かかっている
→後になれば知識が増え、スムーズにできるようになる

**Comment by FukumotoHaruki** [comment]
今後は、Excelファイルを使ってまとめていく
変更にIDを振る

**Comment by FukumotoHaruki** [comment]
![lines2](https://user-images.githubusercontent.com/41629158/47550059-f5cc4100-d938-11e8-902a-1aecd4e5a0b0.png)

**Comment by FukumotoHaruki** [comment]
これまでに確認した修正について
・追加だけをしていることが多い（削除がされていないので、変更ではない）

変更内容の確認
小
・スペースの追加・削除
・インデントをつける
・クラス名の変更
・変数への代入値を変更
中
大
・if文を拡張する
その他
・コメントの変更
・デバッグログの内容の変更
・importの変更
？
・インスタンス変数の参照行の変更
・sudoコマンドの所有者の変更

**Comment by FukumotoHaruki** [comment]
現在、想定している変更が見つかっていないが、
存在はしていると考えているのでもう少し調査を続けていく

**Comment by FukumotoHaruki** [comment]
[Research.xlsx](https://github.com/Wakayama-SocSEL/Fukumoto/files/2541423/Research.xlsx)

**Comment by akinori-i** [comment]
研究アイデアのメモ．すぐに返信する必要はないです．来週ぐらいにどこかで相談できると嬉しいです．

福本君が今読んでいるコードレビュー結果の中で，出力としては等価だけど，プログラムが変更・修正されたという例はなかったですか？
例えば
```
if(a < b+c){ ... }
```
というのが
```
x = b+c;
if(a < x){ ... }
```
みたいな，構造的には同じだけど，パフォーマンスや将来の保守性を考えて修正されたなど．
これは富士通研との共同研究で期待されている研究ネタなんだけど，もし中規模のが見つからないようであれば，小規模も含めてこういう研究するのもありかと．．．上田君の協力も少し必要になると思うけど．
関連研究は以下の通り．
- Kayak: Safe Semantic Refactoring to Java Streams
- Using Program Synthesis for Program Analysis
- Program synthesis: challenges and opportunities
- Semantic Program Repair Using a Reference Implementation
- Overfitting in Semantics-based Automated Program Repair
- Automated Patch Extraction via Syntax- and Semantics-Aware Delta Debugging on Source Code Changes

もう一つのネタは，コーディングルールが時系列で進化していくというネタ．それほど大きくはないけど，AIとかが早く今の時代には面白そう．

個人的には前者のネタが好きです．汎用性が高そうだし．加えて，福元君が将来的にやりたいことに近い気がするし．

**Comment by FukumotoHaruki** [comment]
出力が等価である変更として
```
self._conn = MySQLDriver.get_connection(parsed_url, options)
self.acquired = False
```
が
```
self.acquired = False
self._conn = MySQLDriver.get_connection(parsed_url, options)
```
という記述行の変更や
```
export_location = self._get_share_helper(share['share_proto']).create_export(dataset_name)",
return export_location
```
が
```
return self._get_share_helper(share['share_proto']).create_exports(dataset_name)
```
returnの返り値の変更
また、変数の中身は変わらず、名前だけの変更もあります。
確かに、中規模の変更がなければ、前者のネタも面白そうだと感じます。
ただ、このような変更がまだ複数あるのかは分からないので急いで調査を進めます。
相談に関しては、木曜日にできないかと考えています。
また、相談について連絡させていただきます。

**Comment by FukumotoHaruki** [comment]
名前の変更や行の変更については、パターンなどはありそう？

変数に代入するのをやめて、returnの返り値として直接使う
<img width="634" alt="manila_2fshare_2fdrivers_2fzfsonlinux_2fdriver_py_json" src="https://user-images.githubusercontent.com/41629158/48247506-056a8000-e437-11e8-9833-e2df67fd3b62.png">
<img width="657" alt="gbpservice_2fneutron_2fservices_2fservicechain_2fplugins_2fncp_2fnode_drivers_2fnfp_node_driver_py_json" src="https://user-images.githubusercontent.com/41629158/48247511-0b606100-e437-11e8-862d-9d8ab0948751.png">
